#!/bin/bash
set -e

case "$1" in
    purge)
        rm -rf /etc/qssh
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload || true
        fi
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
