#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop qsshd.service || true
            systemctl disable qsshd.service || true
        fi
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
