#!/usr/bin/env python3
"""Validate that a commit message follows type(scope): description."""

import re
import sys

TYPES = {
    "feat", "fix", "docs", "style", "refactor",
    "test", "chore", "ci", "perf", "revert", "build",
}
SCOPES = {"qssh", "qsshd", "core", "bootstrap", "keygen", "packaging", "ci"}

PATTERN = re.compile(r"^(?P<type>\w+)\((?P<scope>[^)]+)\)(?P<breaking>!)?:\s+\S")


def main():
    msg_file = sys.argv[1]
    with open(msg_file, encoding="utf-8") as f:
        subject = f.readline().strip()

    # Ignore merge commits and fixups generated by git itself.
    if subject.startswith(("Merge ", "Revert ", "fixup! ", "squash! ")):
        sys.exit(0)

    m = PATTERN.match(subject)
    if not m:
        _fail(subject, "must match type(scope): description")

    t = m.group("type")
    s = m.group("scope")

    if t not in TYPES:
        _fail(subject, f"unknown type {t!r}. Allowed: {', '.join(sorted(TYPES))}")
    if s not in SCOPES:
        _fail(subject, f"unknown scope {s!r}. Allowed: {', '.join(sorted(SCOPES))}")


def _fail(subject, reason):
    print(f"[commit-msg] {reason}")
    print(f"  got: {subject!r}")
    print(f"  expected: type(scope): description")
    print(f"  types:  {', '.join(sorted(TYPES))}")
    print(f"  scopes: {', '.join(sorted(SCOPES))}")
    sys.exit(1)


if __name__ == "__main__":
    main()
